## Fourier analysis

### 1. Measure theory

Measure theory provides a rigorous and unified framework to study fundamental notions such as _length_, _area_, _volume_, etc.

Let us begin with a simplified setting. We know from basic courses on Euclidean Geometry how to compute the volume of elementary subsets of \(\mathbb{R}^{3}\). For instance, cubes and rectangular cuboids

\[\mathcal{L}^{3}([0,1]^{3})=1\,,\quad\mathcal{L}^{3}([0,1/2]^{2}\times[0,1])= \frac{1}{4}\,, \tag{1}\]

where \(\mathcal{L}^{3}\) denotes the 3-dimensional volume.

We also know that the volume is _additive_: The volume of a disjoint union of cubes is the sum of the volumes of each cube.

It makes also sense to consider countable family of cubes and cuboids. When disjoint, we expect the total volume to be the infinite sum of the volumes of each element. This property is called _\(\sigma\)-additivity_.

By means of countable unions of cubes we can approximate more complicated objects (e.g. cylinders, balls, etc.) and compute their volumes.

Here is a fundamental question: Which subsets of \(\mathbb{R}^{3}\) can we calculate the volume of, while preserving essential characteristics such as \(\sigma\)-additivity of the volume?

One might hope to compute the volume of every subset of \(\mathbb{R}^{3}\), but this turns out to be impossible. The most famous example is the so-called _Banach-Tarsky paradox_: It is possible to decompose the 3-dimensional ball \(B_{1}(0)\) into five disjoint pieces and reassemble them to get two disjoint balls of radius one. In particular, if we extend the notion of volume to these pieces, then the measure cannot be additive.

On the other hand these pieces are very patological, and never show up in applications. So, the natural strategy is to keep them out of the family of _measurable_ sets.

At this point, we have a clear necessity to identify a sub-family \(\mathcal{A}\subset\mathcal{P}(\mathbb{R}^{3})\) of _measurable sets_.

Let us approach the problem by first identifying the properties that we want on \(\mathcal{A}\).